import type { GalleryImage } from "@/lib/types";
import manifest from "./gallery-manifest.json";

// The Centre's photo collection. Images and manifest are generated by
// scripts/build-gallery.py from the organised archive in medtech-media/img/.
//
// Metadata rules:
//  - `alt` describes what is visible (per source folder).
//  - `event` / `caption` are set only where the event is confirmed by signage in the
//    photos themselves; everything else is left blank rather than guessed.
//  - `date` is the photo's export/camera timestamp.

interface ManifestRow {
  file: string;
  folder: string;
  width: number;
  height: number;
  date: string | null;
  color: string;
}

/** Visible-content alt text, by archive folder slug. */
const ALT: Record<string, string> = {
  "orientation-batch-2024": "Students and faculty during the orientation of the 2024 batch",
  "certificate-ceremony": "Certificates being presented on stage",
  "invited-seminar": "Speaker presenting to an audience in a lecture theatre",
  "startup-exhibition": "Founders at a startup exhibition booth",
  "lab-visit": "Group gathered in a computer lab",
  "iitj-convocation-2024": "IIT Jodhpur Convocation 2024",
  "auditorium-event": "Session in a campus auditorium",
  awards: "Award plaques and a ceremony on stage",
  "group-and-workspace": "Students and faculty at the Centre",
  "icmi-2025": "Indian Conference on MedTech Innovations (ICMI) 2025",
  award: "Award presentation on stage",
  "new-workspace": "The Centre's new workspace being furnished",
  "iitj-convocation-2025": "IIT Jodhpur Convocation 2025",
  "iitj-foundation-day-2025": "Award presentation at IIT Jodhpur Foundation Day 2025",
  "tie-rajasthan-recognition": "Cheque presentation at a TiE Rajasthan event",
  "meeting-session": "Discussion session around a meeting-room table",
  ceremony: "Ceremonial event",
  "genpact-master-student-fellowships": "Announcement of Genpact Master Student Fellowship recipients",
  exhibition: "Visitors at an exhibition stall",
  "ai-exhibition": "Visitors at a technology exhibition",
  "workshop-session": "Participants working around tables during a session",
  "certificate-distribution": "Certificate distribution",
  "iitj-convocation-2026": "IIT Jodhpur Convocation 2026, Class of 2026",
  "5th-convocation": "Degree presentation at a convocation ceremony",
  "iitj-foundation-day-2026": "IIT Jodhpur Foundation Day 2026",
  "event-hall": "Audience seated at tables in an event hall",
  "group-event": "Group photograph in an auditorium",
  "startup-meet-and-greet-11": "Startup Meet & Greet 11.0",
  undated: "IBRO Exchange Fellowships 2026 announcement",
};

/** Events confirmed by what the photos show (banners, slides, posters). */
const EVENT: Record<string, string> = {
  "orientation-batch-2024": "Orientation, batch of 2024",
  "iitj-convocation-2024": "IIT Jodhpur Convocation 2024",
  "icmi-2025": "ICMI 2025",
  "iitj-convocation-2025": "IIT Jodhpur Convocation 2025",
  "iitj-foundation-day-2025": "IIT Jodhpur Foundation Day 2025",
  "genpact-master-student-fellowships": "Genpact Master Student Fellowships",
  "iitj-convocation-2026": "IIT Jodhpur Convocation 2026",
  "iitj-foundation-day-2026": "IIT Jodhpur Foundation Day 2026",
  "startup-meet-and-greet-11": "Startup Meet & Greet 11.0",
  undated: "IBRO Exchange Fellowships 2026",
};

/** Hand-picked for the homepage, in display order (first = large tile). Ids = file names. */
export const FEATURED_ORDER = [
  "2026-06-06_13-42-25_2", // Class of 2026
  "2026-08-08_11-07-38",
  "2025-02-15_15-17-01", // ICMI 2025 delegates
  "2024-08-03_19-54-31", // 2024 batch orientation outing
  "2026-09-13_12-40-29_2", // Startup Meet & Greet 11.0
];
const FEATURED = new Set(FEATURED_ORDER);

const slugOf = (folder: string) => folder.replace(/^\d{4}-\d\d-\d\d_/, "");

export const galleryImages: GalleryImage[] = (manifest as ManifestRow[]).map((row) => {
  const slug = slugOf(row.folder);
  const id = row.file.replace(/\.jpg$/, "");
  const event = EVENT[slug];
  return {
    id,
    src: `/images/gallery/${row.file}`,
    alt: ALT[slug] ?? "Photograph from the Medical Technology Centre",
    width: row.width,
    height: row.height,
    date: row.date ?? undefined,
    event,
    caption: event,
    color: row.color,
    featured: FEATURED.has(id),
  };
});
